### ISSUE TITLE
Error with stopping listening

### ISSUE THREAD

**Issue by kimprice** [kimprice/snippetbox#3]
This error seems to happen when speaking and then turning listening off at the same time. So probably it has to do with data still attempting to process and log after the listener was removed.

Full error:
Error: write after end	at writeAfterEnd (snippetbox/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:261:12)	at Pumpify.write (snippetbox/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:305:21)	at Socket.ondata (internal/streams/readable.js:719:22)	at Socket.emit (events.js:327:22)	at addChunk (internal/streams/readable.js:309:12)	at readableAddChunk (internal/streams/readable.js:284:9)	at Socket.push (internal/streams/readable.js:223:10)	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) (at Pumpify.emit (events.js:327:22))

**Comment by kimprice** [comment]
I think this commit also fixed this issue: 6c5ad0e4d3e69ec2d60cef342dcb519bdec6a9f6
